### ISSUE TITLE
[feature request] stream readline?

### ISSUE THREAD

**Issue by u007** [richard-viney/file_streams#1]
anytime to implement this?

thank you

**Comment by richard-viney** [comment]
Text streams that support reading UTF-8 chars and lines are implemented on a branch here: https://github.com/richard-viney/file_streams/tree/text-streams

Please test it out if you're able to.

**Comment by richard-viney** [comment]
Released in v0.3.0 just now.

**Comment by u007** [comment]
nice thank you
